# Based on https://github.com/im85288/service.upnext/blob/master/.github/workflows/release.yml
name: Make Release
on:
  push:
    tags:
      - 'v*'
      - '*-dev'

jobs:
  release:
    if: github.repository == 'anxdpanic/plugin.video.composite_for_plex'

    name: Make Release
    runs-on: ubuntu-latest

    steps:
      - name: Release Status
        id: release
        run: |
          version=${GITHUB_REF/refs\/tags\//}
          if [[ $version == *-dev ]] ;
          then
            echo ::set-output name=pre-release::true
          else
            echo ::set-output name=pre-release::false
          fi

      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-utils xmlstarlet zip

      - name: Get Changelog
        id: changelog
        run: |
          changes=$(xmlstarlet sel -t -v '//news' -n addon.xml)
          changes="${changes//'%'/'%25'}"
          changes="${changes//$'\n'/'%0A'}"
          changes="${changes//$'\r'/'%0D'}"
          echo ::set-output name=changes::$changes
        working-directory: ${{ github.event.repository.name }}

      - name: Create Zip (Jarvis)
        id: zip-jarvis
        run: |
          git reset
          git checkout .
          git clean -fdx
          mv .git ..
          rm -rf .??*
          rm *.md
          version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
          filename=${{ github.event.repository.name }}-${version}.zip
          cd ..
          zip -r $filename ${{ github.event.repository.name }}
          mv .git ${{ github.event.repository.name }}
          echo ::set-output name=filename::$filename
        working-directory: ${{ github.event.repository.name }}

      - name: Create Zip (Leia)
        id: zip-leia
        run: |
          git reset
          git checkout .
          git clean -fdx
          git apply .patches/leia.patch
          mv .git ..
          rm -rf .??*
          rm *.md
          version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
          filename=${{ github.event.repository.name }}-leia-${version}.zip
          cd ..
          zip -r $filename ${{ github.event.repository.name }}
          mv .git ${{ github.event.repository.name }}
          echo ::set-output name=filename::$filename
        working-directory: ${{ github.event.repository.name }}

      - name: Create Zip (Matrix)
        id: zip-matrix
        run: |
          git reset
          git checkout .
          git clean -fdx
          git apply .patches/matrix.patch
          mv .git ..
          rm -rf .??*
          rm *.md
          version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
          xmlstarlet ed -L -u '/addon/@version' -v "${version}+matrix.1" addon.xml
          version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
          filename=${{ github.event.repository.name }}-${version}.zip
          cd ..
          zip -r $filename ${{ github.event.repository.name }}
          mv .git ${{ github.event.repository.name }}
          echo ::set-output name=filename::$filename
        working-directory: ${{ github.event.repository.name }}

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: ${{ steps.release.outputs.pre-release }}

      - name: Upload Zip (Jarvis)
        id: upload-jarvis
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: ${{ steps.zip-jarvis.outputs.filename }}
          asset_path: ${{ steps.zip-jarvis.outputs.filename }}
          asset_content_type: application/zip

      - name: Upload Zip (Leia)
        id: upload-leia
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: ${{ steps.zip-leia.outputs.filename }}
          asset_path: ${{ steps.zip-leia.outputs.filename }}
          asset_content_type: application/zip

      - name: Upload Zip (Matrix)
        id: upload-matrix
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_name: ${{ steps.zip-matrix.outputs.filename }}
          asset_path: ${{ steps.zip-matrix.outputs.filename }}
          asset_content_type: application/zip
